@url = localhost:5000

### Create user
POST http://{{url}}/api/auth/signup
Content-Type: application/json

{
  "email": "availrevail666@gmail.com",
  "password": "test12345"
}

### Signin user
POST http://{{url}}/api/auth/signin
Content-Type: application/json

{
  "email": "availrevail666@gmail.com",
  "password": "test12345"
}

### Refresh token
POST http://{{url}}/api/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTc0MjcxNSwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNzQyNzE1LCJleHAiOjE2ODE3NDYzMTUsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.E-9rcuJ0qroBKEWqW_Oe44X2uh0eptfhK-4pWbeJP9Sb-PEll0PP9kEtkuVXtNSeJG1b_br8budwL0nSnwczQ-0XhRCVHRFKWLnCfaRDZma0lZ1ScdnZnWP-B1M0_UeXkpgPfG0HUQYgMShXGoNXvmZvYLRGNV5NueglmHWqrh1Gt0NDHsdM23c26t_6cTLY4IxPPdhOEaib5Qh43dCfZMCwQ4cW1fWaZwbjvhJ5iFbRUVc_ZFcvh89P_PJU-B-wsMktaJAD2ZdkSOxZyKN0N-xbCaeWtj3LSzRfJC016xzjwgCdyIZUoPUJ3kzEMJ4ixVgGn0DluAeFT5sVpScbNQ


{
  "refresh_token": "APJWN8f0fX_lqLrihsoku47SVoMsG0Twttqj03EFF-bPaQDb4X4GPmQPVDQCq3T-Iu0Ob51ERxmP0gVQOFExqulZ2NW8eH3bn7hJG6nW1KJTA0QKgwzo8aDw-kNBDiDDgg7ouetkYfs4LyGvJQkm4VAPRqAd9fts-Uoo3ebkioSgQzZscwCblUM2veOA_N4bU5L9ZX07vMCCt7_xi68xp-6BavRCOxQu1PC15AcZC0uwKub8o8-0lvo"
}

### Get all resumes
GET http://{{url}}/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTc0MDUxNiwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNzQwNTE2LCJleHAiOjE2ODE3NDQxMTYsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.c8-gK2GEwpegEgt5CCFf5frB8of_i_VE47Y5WZd_lMImDaQhQbiDN9JFKoNvZp22wWLr16Aic4SsdI-GizVmW3ZCRJIKhV8VPXlW5Nfs_H0UcMjKtvYtuIhWYpihQOQz9TLrVYAij0krp_7wBnbAg6_U7mAGi5v0f_0Fkj4tomA5m6bvpkpqcdsWu3zlVP_cNb6g9k-4cvQvrcA5OZqgFQ61bfsXDKr2CIp-IZuKROj5R7L4OM7jiVg02J1tvQ-hEzlfaw9WveO1YawJAZs8fWMI0WdYeYFzqb54-uafLtoP5HDyKSh2LJO8tzwSgSG07oi_ZUM_MEGNU-60XqVsBw

### Get resume by id
GET http://{{url}}/api/075dbd6a-cf3c-4b4a-bd3b-a4f6053583
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTc0MDUxNiwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNzQwNTE2LCJleHAiOjE2ODE3NDQxMTYsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.c8-gK2GEwpegEgt5CCFf5frB8of_i_VE47Y5WZd_lMImDaQhQbiDN9JFKoNvZp22wWLr16Aic4SsdI-GizVmW3ZCRJIKhV8VPXlW5Nfs_H0UcMjKtvYtuIhWYpihQOQz9TLrVYAij0krp_7wBnbAg6_U7mAGi5v0f_0Fkj4tomA5m6bvpkpqcdsWu3zlVP_cNb6g9k-4cvQvrcA5OZqgFQ61bfsXDKr2CIp-IZuKROj5R7L4OM7jiVg02J1tvQ-hEzlfaw9WveO1YawJAZs8fWMI0WdYeYFzqb54-uafLtoP5HDyKSh2LJO8tzwSgSG07oi_ZUM_MEGNU-60XqVsBw

### Create resume
POST http://{{url}}/api/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY2MDczMywidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjYwNzMzLCJleHAiOjE2ODE2NjQzMzMsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Sqr2X38h5EGgV5UyTu434pGMffxdGFVsTXj8UrJxtiY1kJBalzxmgXKO9WjHyWIsBGWAh8-99edEEhA4pvONhrRjZ5Oh9vjnSKaQrZpHaSm3n9JkJ1gV6RYK6PIhvOkMzNx3OxxJkgXwd5J735sMji5ePt68fsaXXwScx5Ngj_gXriwDmmk6IjVVS8HWtw4f2AJHUsale0vgk9vhF-UA81rBAPD1l24SHEl0TN_T_DwN8xBIrmGl7qaunYb5Z0vlBMO7Tx8wOpFjxbOS6HPJ7ubMKK7vwMdLl5Oi6jt8yf-ASZ0gx0pCAySHhe2kdsqs6mP78GnZ4glt4ZZH_eeOJQ

{
  "name": "my first resume"
}

### Delete resume by id
DELETE http://{{url}}/api/95e57d3a-2f54-4540-af10-18cb9a99ed6d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY1NjM1NCwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjU2MzU0LCJleHAiOjE2ODE2NTk5NTQsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.nHHj8uIOlTN85Ipy9EBBtaJgZRsZ02v98NdLYNSllEGbgcd9EG2LC2YQX4sgEgpWhEAe1jgF_VnzMUx16sTkbz8yGPHmfL1N0gEiG4rf8AR-YX0vf8KSQ-nM9IaNXtEPI5KvtavSSWevRAIdA26eDjNemlpeFnF971uZ2Ddk5CYOQMlUJWaVQftdwhTIQ0aA-UWA6Elr_c-pwxpTPgp7UvGw1wDAiZ-4pKLbmaPqqMAHLZ4wChg8i5HrBMDkoJ9Vp6NWyLtmsEdoKraLq67WKoXJlF2M0kQ2RqmBjMDsCNco6Qj3cM49frr_UCNdggV1TbZfbqaH2M2owu4ae6ZulA

### Create Experience 1
POST http://{{url}}/api/experience
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY2MDczMywidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjYwNzMzLCJleHAiOjE2ODE2NjQzMzMsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Sqr2X38h5EGgV5UyTu434pGMffxdGFVsTXj8UrJxtiY1kJBalzxmgXKO9WjHyWIsBGWAh8-99edEEhA4pvONhrRjZ5Oh9vjnSKaQrZpHaSm3n9JkJ1gV6RYK6PIhvOkMzNx3OxxJkgXwd5J735sMji5ePt68fsaXXwScx5Ngj_gXriwDmmk6IjVVS8HWtw4f2AJHUsale0vgk9vhF-UA81rBAPD1l24SHEl0TN_T_DwN8xBIrmGl7qaunYb5Z0vlBMO7Tx8wOpFjxbOS6HPJ7ubMKK7vwMdLl5Oi6jt8yf-ASZ0gx0pCAySHhe2kdsqs6mP78GnZ4glt4ZZH_eeOJQ

{
  "resume_id": "2dfbd652-2a60-4a94-87db-9b26acaf840e",
  "company_name": "Autobahn Security",
  "job_desc": "Engineering Manager",
  "month_from": 8,
  "year_from": 2020,
  "month_to": null,
  "year_to": null,
  "is_present": true,
  "additional_info": "Leadership",
  "description": "Managing 2 squads (around 12 people) - Responsible for individual improvement",
  "formatted": "<ul> <li>Managing 2 squads (around 12 people)</li> <li>Responsible for individual improvement</li></ul>"
}

### Create Experience 2
POST http://{{url}}/api/experience
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY2MDczMywidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjYwNzMzLCJleHAiOjE2ODE2NjQzMzMsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Sqr2X38h5EGgV5UyTu434pGMffxdGFVsTXj8UrJxtiY1kJBalzxmgXKO9WjHyWIsBGWAh8-99edEEhA4pvONhrRjZ5Oh9vjnSKaQrZpHaSm3n9JkJ1gV6RYK6PIhvOkMzNx3OxxJkgXwd5J735sMji5ePt68fsaXXwScx5Ngj_gXriwDmmk6IjVVS8HWtw4f2AJHUsale0vgk9vhF-UA81rBAPD1l24SHEl0TN_T_DwN8xBIrmGl7qaunYb5Z0vlBMO7Tx8wOpFjxbOS6HPJ7ubMKK7vwMdLl5Oi6jt8yf-ASZ0gx0pCAySHhe2kdsqs6mP78GnZ4glt4ZZH_eeOJQ

{
  "resume_id": "2dfbd652-2a60-4a94-87db-9b26acaf840e",
  "company_name": "Security Research Labs",
  "job_desc": "Senior Software Engineer",
  "month_from": 3,
  "year_from": 2019,
  "month_to": 7,
  "year_to": 2020,
  "is_present": false,
  "additional_info": "Leadership",
  "description": "Responsible for maintaining reporting module",
  "formatted": "<ul> <li>Managing reporting module</li> <li>Responsible for code quality</li></ul>"
}

### Get Experiences
GET http://{{url}}/api/experience/2dfbd652-2a60-4a94-87db-9b26acaf840e/resume
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY2MDczMywidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjYwNzMzLCJleHAiOjE2ODE2NjQzMzMsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Sqr2X38h5EGgV5UyTu434pGMffxdGFVsTXj8UrJxtiY1kJBalzxmgXKO9WjHyWIsBGWAh8-99edEEhA4pvONhrRjZ5Oh9vjnSKaQrZpHaSm3n9JkJ1gV6RYK6PIhvOkMzNx3OxxJkgXwd5J735sMji5ePt68fsaXXwScx5Ngj_gXriwDmmk6IjVVS8HWtw4f2AJHUsale0vgk9vhF-UA81rBAPD1l24SHEl0TN_T_DwN8xBIrmGl7qaunYb5Z0vlBMO7Tx8wOpFjxbOS6HPJ7ubMKK7vwMdLl5Oi6jt8yf-ASZ0gx0pCAySHhe2kdsqs6mP78GnZ4glt4ZZH_eeOJQ

