@url = localhost:5000

### Create user
POST http://{{url}}/api/auth/signup
Content-Type: application/json

{
  "email": "availrevail666@gmail.com",
  "password": "test12345"
}

### Signin user
POST http://{{url}}/api/auth/signin
Content-Type: application/json

{
  "email": "availrevail666@gmail.com",
  "password": "test12345"
}

### Get all resumes
GET http://{{url}}/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY0OTMxNSwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjQ5MzE1LCJleHAiOjE2ODE2NTI5MTUsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.pOeWzMKqL60nK6UCxysavd2goE5ttRgxY8ZvWyNyEytdKABQUkATgnxr-52YXefwa-f4hKzQE7F_wwgOEIjcNEloBCf0k6KZnjhJDjxASd1l4-w3r5JQ1TyDzgxR1biiu4lhmFOKNztxJ3U-XTZ7jJS2Qiqo9SCI2D0rlFswMMC4xmLLpElBcIZFh9yvUmDvSchsQ_8q05ZSuDVFE_Q0bB81b37ACP1hUhMUWKiEuUgVcZYIi7wZkkW7vV1FBgQ2qfyc_1HPS4BFeQ2nUm2JTzgv7mp1drwJxObqG2L38ZyF8i4GfbJ9maIdqoYg4QLp_aBjODmhS3QnBGWQgCDLJg

### Get resume by id
GET http://{{url}}/api/834e5cd8-d9bf-49a5-b39f-5ed30ea1fdbe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY0Nzc5MiwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjQ3NzkyLCJleHAiOjE2ODE2NTEzOTIsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.V291y5wHW769Do_8_Mhjhaj9FQ9hrTXekOQI_e3xhxxtOgQ2k6F5NX3qYZnfWMiFWVYPFCV3BL2zvTnYj-UfkVVMoV-kkXWoY292DmfNgPXX_mGQPJXUgnc71synQLOPYCbJZ8Kt67twi70w3NBWc4VLtozQvBU_SC88QBKSwixYQvyExmk9T7T3JC9oGGb9LJ5ydkBOrFwKM57pM9hJCmWAnZlEdE0RzBXMejoRjVvikgNVYqWQtIQd2qmLgGDnDwPDG6huPlJMgSAez1lO3ELQm5HdU-0PO-oSfvJHO24_tP8b7vozEhTAiKoPX-jsGrTEygmhBwD9_OUdg4eO7A

