@url = localhost:5000

### Create user
POST http://{{url}}/api/auth/signup
Content-Type: application/json

{
  "email": "availrevail666@gmail.com",
  "password": "test12345"
}

### Signin user
POST http://{{url}}/api/auth/signin
Content-Type: application/json

{
  "email": "availrevail666@gmail.com",
  "password": "test12345"
}

### Get all resumes
GET http://{{url}}/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY1NjM1NCwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjU2MzU0LCJleHAiOjE2ODE2NTk5NTQsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.nHHj8uIOlTN85Ipy9EBBtaJgZRsZ02v98NdLYNSllEGbgcd9EG2LC2YQX4sgEgpWhEAe1jgF_VnzMUx16sTkbz8yGPHmfL1N0gEiG4rf8AR-YX0vf8KSQ-nM9IaNXtEPI5KvtavSSWevRAIdA26eDjNemlpeFnF971uZ2Ddk5CYOQMlUJWaVQftdwhTIQ0aA-UWA6Elr_c-pwxpTPgp7UvGw1wDAiZ-4pKLbmaPqqMAHLZ4wChg8i5HrBMDkoJ9Vp6NWyLtmsEdoKraLq67WKoXJlF2M0kQ2RqmBjMDsCNco6Qj3cM49frr_UCNdggV1TbZfbqaH2M2owu4ae6ZulA

### Get resume by id
GET http://{{url}}/api/075dbd6a-cf3c-4b4a-bd3b-a4f605358398
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY1NjM1NCwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjU2MzU0LCJleHAiOjE2ODE2NTk5NTQsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.nHHj8uIOlTN85Ipy9EBBtaJgZRsZ02v98NdLYNSllEGbgcd9EG2LC2YQX4sgEgpWhEAe1jgF_VnzMUx16sTkbz8yGPHmfL1N0gEiG4rf8AR-YX0vf8KSQ-nM9IaNXtEPI5KvtavSSWevRAIdA26eDjNemlpeFnF971uZ2Ddk5CYOQMlUJWaVQftdwhTIQ0aA-UWA6Elr_c-pwxpTPgp7UvGw1wDAiZ-4pKLbmaPqqMAHLZ4wChg8i5HrBMDkoJ9Vp6NWyLtmsEdoKraLq67WKoXJlF2M0kQ2RqmBjMDsCNco6Qj3cM49frr_UCNdggV1TbZfbqaH2M2owu4ae6ZulA

### Create resume
POST http://{{url}}/api/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY1NjM1NCwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjU2MzU0LCJleHAiOjE2ODE2NTk5NTQsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.nHHj8uIOlTN85Ipy9EBBtaJgZRsZ02v98NdLYNSllEGbgcd9EG2LC2YQX4sgEgpWhEAe1jgF_VnzMUx16sTkbz8yGPHmfL1N0gEiG4rf8AR-YX0vf8KSQ-nM9IaNXtEPI5KvtavSSWevRAIdA26eDjNemlpeFnF971uZ2Ddk5CYOQMlUJWaVQftdwhTIQ0aA-UWA6Elr_c-pwxpTPgp7UvGw1wDAiZ-4pKLbmaPqqMAHLZ4wChg8i5HrBMDkoJ9Vp6NWyLtmsEdoKraLq67WKoXJlF2M0kQ2RqmBjMDsCNco6Qj3cM49frr_UCNdggV1TbZfbqaH2M2owu4ae6ZulA

{
  "name": "my second resume"
}

### Delete resume by id
DELETE http://{{url}}/api/95e57d3a-2f54-4540-af10-18cb9a99ed6d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4MjNkMWE0MTg5ZjI3NThjYWI4NDQ4ZmQ0MTIwN2ViZGZhMjVlMzkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVzdW1lLWJ1aWxkZXItYzk5ZmMiLCJhdWQiOiJyZXN1bWUtYnVpbGRlci1jOTlmYyIsImF1dGhfdGltZSI6MTY4MTY1NjM1NCwidXNlcl9pZCI6IlRiT25UOXR6WHVkNVVYN3JIZ0ZabWw4RkpydzIiLCJzdWIiOiJUYk9uVDl0elh1ZDVVWDdySGdGWm1sOEZKcncyIiwiaWF0IjoxNjgxNjU2MzU0LCJleHAiOjE2ODE2NTk5NTQsImVtYWlsIjoiYXZhaWxyZXZhaWw2NjZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImF2YWlscmV2YWlsNjY2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.nHHj8uIOlTN85Ipy9EBBtaJgZRsZ02v98NdLYNSllEGbgcd9EG2LC2YQX4sgEgpWhEAe1jgF_VnzMUx16sTkbz8yGPHmfL1N0gEiG4rf8AR-YX0vf8KSQ-nM9IaNXtEPI5KvtavSSWevRAIdA26eDjNemlpeFnF971uZ2Ddk5CYOQMlUJWaVQftdwhTIQ0aA-UWA6Elr_c-pwxpTPgp7UvGw1wDAiZ-4pKLbmaPqqMAHLZ4wChg8i5HrBMDkoJ9Vp6NWyLtmsEdoKraLq67WKoXJlF2M0kQ2RqmBjMDsCNco6Qj3cM49frr_UCNdggV1TbZfbqaH2M2owu4ae6ZulA
